version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    pre_install:
      - pip install mkdocs-material  # replace with your theme if different

python:
  install:
    - requirements: requirements.txt  # since it's in the root

sphinx:
  configuration: false  # explicitly disable Sphinx

mkdocs:
  configuration: mkdocs.yml  # assumes this is in the root
