version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    pre_install:
      - pip install mkdocs-material  # or any other mkdocs theme you're using

python:
  install:
    - requirements: requirements.txt  # this is in the root

mkdocs:
  configuration: mkdocs.yml
